import type { Day, Resource } from './types';

export const studyDays: Day[] = [
  {
    dayNumber: 1,
    date: 'Dec 5',
    blocks: [
      {
        id: 'day1-java-1',
        timeRange: '8:00–10:00',
        title: 'Java OOP Crash Course',
        topic: 'Java',
        description: 'Focus topics: Classes and objects, Constructors, this keyword, toString(), Static vs instance members.',
        completed: false,
        tasks: [
          {
            id: 'day1-java-1-task-1',
            description: 'Watch Bro Code Java Full Course, jump to OOP section (~4:00:00 mark) at 1.75x',
            completed: false,
          },
          {
            id: 'day1-java-1-task-2',
            description: 'While watching OOP part, note examples of: Class definition, Object instantiation, Constructor overloading, this usage in constructors and setters',
            completed: false,
          },
        ],
        flashcards: [
          { id: 'f1', front: 'What is this?', back: 'this is a reference to the current object; used to disambiguate fields from parameters and to call other constructors/methods.', known: false },
          { id: 'f2', front: 'Constructor rules', back: 'Same name as class, no return type, can be overloaded, called automatically on new, if no constructors defined → default constructor exists; once any constructor is defined, default no-arg is not generated.', known: false },
          { id: 'f3', front: 'Access modifiers: private', back: 'Accessible only inside the declaring class.', known: false },
          { id: 'f4', front: 'Access modifiers: public', back: 'Accessible from any class.', known: false },
          { id: 'f5', front: 'Access modifiers: protected', back: 'Accessible in same package + subclasses in other packages.', known: false },
          { id: 'f6', front: 'Access modifiers: default (package-private)', back: 'No modifier keyword; accessible in the same package only.', known: false },
          { id: 'f7', front: 'Purpose of toString()', back: 'Human-readable string representation; called automatically by System.out.println(obj); override to show object state.', known: false },
          { id: 'f8', front: 'Static vs instance – fields', back: 'Static belongs to the class (one copy), instance belongs to each object.', known: false },
          { id: 'f9', front: 'Static vs instance – methods', back: 'Static methods can be called via class name; cannot access instance fields directly; instance methods belong to object.', known: false },
          { id: 'f10', front: 'Can constructors be static?', back: 'No, constructors are not static; they\'re invoked on object creation.', known: false },
          { id: 'f11', front: 'Can constructors return values?', back: 'No explicit return type; implicitly return the constructed object.', known: false },
          { id: 'f12', front: 'Overloading vs overriding (summary card)', back: 'Overloading = same name, different parameter list within same class; overriding = same signature in subclass, compatible return type, not more restrictive access.', known: false },
          { id: 'f13', front: 'Array basics', back: 'Arrays are objects; length field; indexing from 0; passed by reference.', known: false },
          { id: 'f14', front: '2D array basics', back: 'Arrays of arrays; jagged; m.length = number of rows; m[i].length = length of row i.', known: false },
          { id: 'f15', front: 'Default values for fields vs locals', back: 'Fields get defaults (0, 0.0, null, false); local variables do not, must be explicitly initialized before use.', known: false },
          { id: 'f16', front: 'Local variables and scope', back: 'Only visible within their block; no default; can\'t use before assignment.', known: false },
        ],
      },
      {
        id: 'day1-java-2',
        timeRange: '10:00–11:30',
        title: 'Classes Practice',
        topic: 'Java',
        description: 'Code from scratch, no copy-paste',
        completed: false,
        tasks: [
          {
            id: 'day1-java-2-task-1',
            description: 'Circle class: Private field: double radius. Constructor: Circle(double radius). Methods: getRadius(), getArea() (πr²). Override toString() using String.format("Circle(radius=%.2f, area=%.2f)", radius, getArea()).',
            completed: false,
          },
          {
            id: 'day1-java-2-task-2',
            description: 'Person class: Private fields: String name, int age. Constructor: Person(String name, int age). Getters: getName(), getAge(). toString() returning "Person(name=..., age=...)".',
            completed: false,
          },
          {
            id: 'day1-java-2-task-3',
            description: 'Rectangle class: Private fields: double width, double height. Constructor, getArea(), getPerimeter(). toString() describing width, height, area, perimeter.',
            completed: false,
          },
        ],
      },
      {
        id: 'day1-java-3',
        timeRange: '11:30–13:00',
        title: 'Arrays & References',
        topic: 'Java',
        description: 'Key concepts: Jagged arrays, Arrays are objects passed by reference',
        completed: false,
        tasks: [
          {
            id: 'day1-java-3-task-1',
            description: 'Implement 10 2D jagged array indexing exercises: Given a declaration, determine m[i].length, m[i][j], or runtime error.',
            completed: false,
          },
          {
            id: 'day1-java-3-task-2',
            description: 'Recreate and solve questions analogous to mock exam Q5, Q31, Q32 (length and indexing in jagged arrays).',
            completed: false,
          },
          {
            id: 'day1-java-3-task-3',
            description: 'Recreate and solve questions analogous to mock exam Q19 and Q30 (arrays passed by reference, reference reassignment).',
            completed: false,
          },
        ],
      },
      {
        id: 'day1-linalg-1',
        timeRange: '14:00–15:30',
        title: 'Matrix Operations',
        topic: 'Linear Algebra',
        description: 'Practice matrix operations',
        completed: false,
        tasks: [
          { id: 'day1-linalg-1-task-1', description: 'Practice matrix addition: 10 problems', completed: false },
          { id: 'day1-linalg-1-task-2', description: 'Practice matrix multiplication: 10 problems; carefully follow the dot-product rule', completed: false },
          { id: 'day1-linalg-1-task-3', description: 'Practice transpose: 10 problems (including rectangular matrices)', completed: false },
          { id: 'day1-linalg-1-task-4', description: 'Use Khan Academy for exercises; verify selected answers with Symbolab', completed: false },
        ],
      },
      {
        id: 'day1-linalg-2',
        timeRange: '15:30–17:30',
        title: 'Row Reduction Bootcamp',
        topic: 'Linear Algebra',
        description: 'Master RREF',
        completed: false,
        tasks: [
          { id: 'day1-linalg-2-task-1', description: 'Watch short Khan Academy RREF video (~15 min at 2x)', completed: false },
          { id: 'day1-linalg-2-task-2', description: 'Row reduce 20 matrices: Start: 3×3 systems. Then: 4×4 and 3×5 matrices. Goal: handle a 4×4 RREF problem in under 5 minutes with correct pivots.', completed: false },
        ],
      },
      {
        id: 'day1-linalg-3',
        timeRange: '17:30–19:00',
        title: 'Leading vs Free Variables',
        topic: 'Linear Algebra',
        description: 'Pivot columns = leading variables. Non-pivot columns = free variables.',
        completed: false,
        tasks: [
          { id: 'day1-linalg-3-task-1', description: '15 problems: Solve Ax = b and express solution sets with parameters (free variables)', completed: false },
          { id: 'day1-linalg-3-task-2', description: '10 problems: Given RREF, identify: Pivot columns, Free columns, Describe solution forms', completed: false },
        ],
      },
      {
        id: 'day1-evening',
        timeRange: '19:30–21:00',
        title: 'Java Review',
        topic: 'Java',
        description: 'Evening review session',
        completed: false,
        tasks: [
          { id: 'day1-evening-task-1', description: 'Review all 15 Java flashcards (3 passes)', completed: false },
          { id: 'day1-evening-task-2', description: 'Re-implement Circle class from memory in under 10 minutes', completed: false },
          { id: 'day1-evening-task-3', description: 'Re-do any arrays or jagged array questions that weren\'t automatic', completed: false },
        ],
      },
    ],
  },
  // Day 2-6 will be added similarly - creating Day 2 as example, then will add rest
  {
    dayNumber: 2,
    date: 'Dec 6',
    blocks: [
      {
        id: 'day2-java-1',
        timeRange: '8:00–9:30',
        title: 'Inheritance Theory',
        topic: 'Java',
        description: 'extends keyword, super() constructor call, method overriding',
        completed: false,
        tasks: [
          { id: 'day2-java-1-task-1', description: 'Watch a focused Java inheritance tutorial (~30 minutes)', completed: false },
        ],
        flashcards: [
          { id: 'f17', front: 'What does super() do?', back: 'Calls the parent class constructor; must be first line in constructor if used.', known: false },
          { id: 'f18', front: 'Constructor execution order in inheritance', back: 'Parent constructor executes first, then child constructor.', known: false },
          { id: 'f19', front: 'Can you override private methods?', back: 'No, private methods are not overridden; they are hidden.', known: false },
          { id: 'f20', front: 'Rules for method overriding', back: 'Same signature, compatible return type (covariant allowed), access level cannot be more restrictive.', known: false },
          { id: 'f21', front: 'Upcasting: Parent p = new Child()', back: 'Reference type is Parent, object type is Child; can call Parent methods, but runtime uses Child implementation if overridden.', known: false },
          { id: 'f22', front: 'instanceof behavior', back: 'Checks if object is instance of class or subclass; returns true for parent class if object is child instance.', known: false },
        ],
      },
      {
        id: 'day2-java-2',
        timeRange: '9:30–11:30',
        title: 'Inheritance Practice',
        topic: 'Java',
        description: 'Animal hierarchy, GeometricObject hierarchy',
        completed: false,
        tasks: [
          { id: 'day2-java-2-task-1', description: 'Animal hierarchy: Animal with name, age, makeSound(). Dog extends Animal: breed, override makeSound(). Cat extends Animal: color, override makeSound(). Test polymorphism: Animal a = new Dog(...); a.makeSound();', completed: false },
          { id: 'day2-java-2-task-2', description: 'GeometricObject hierarchy: Abstract GeometricObject with abstract area(). Rectangle & Triangle implement area().', completed: false },
          { id: 'day2-java-2-task-3', description: 'Recreate mock Q36 pattern: Person → Employee → MyProject. Trace constructor calls and toString().', completed: false },
        ],
      },
      {
        id: 'day2-java-3',
        timeRange: '11:30–13:00',
        title: 'Abstract Classes',
        topic: 'Java',
        description: 'Cannot instantiate, concrete subclasses must implement abstract methods',
        completed: false,
        tasks: [
          { id: 'day2-java-3-task-1', description: 'Watch a short abstract classes tutorial (~20 min)', completed: false },
          { id: 'day2-java-3-task-2', description: 'Solve problems analogous to mock Q2, Q14, Q16 about abstract classes', completed: false },
          { id: 'day2-java-3-task-3', description: 'Code 2 small abstract hierarchies (e.g., Shape → Circle/Rectangle, Account → Checking/Savings)', completed: false },
        ],
      },
      {
        id: 'day2-linalg-1',
        timeRange: '14:00–15:00',
        title: 'Span & Linear Independence Theory',
        topic: 'Linear Algebra',
        description: 'Span = all linear combinations, Linear independence test',
        completed: false,
        tasks: [
          { id: 'day2-linalg-1-task-1', description: 'Watch 3Blue1Brown Essence of Linear Algebra, Part 3 at 2x', completed: false },
        ],
      },
      {
        id: 'day2-linalg-2',
        timeRange: '15:00–17:00',
        title: 'Linear Independence Drills',
        topic: 'Linear Algebra',
        description: '25 problems: Are vectors linearly independent? 15 problems: Is vector b in span?',
        completed: false,
        tasks: [
          { id: 'day2-linalg-2-task-1', description: '25 problems: Are vectors linearly independent? Put vectors as columns, row reduce, check pivot in each column', completed: false },
          { id: 'day2-linalg-2-task-2', description: '15 problems: Is vector b in span {v₁, v₂, v₃}? Set up augmented matrix [v₁ v₂ v₃ | b], row reduce; consistency ↔ b in span', completed: false },
        ],
      },
      {
        id: 'day2-linalg-3',
        timeRange: '17:00–19:00',
        title: 'Rank, Nullity, Basis',
        topic: 'Linear Algebra',
        description: 'rank(A) + nullity(A) = # of columns',
        completed: false,
        tasks: [
          { id: 'day2-linalg-3-task-1', description: 'Skim MIT 18.06 notes (~15 minutes)', completed: false },
          { id: 'day2-linalg-3-task-2', description: '20 problems: Find rank and nullity', completed: false },
          { id: 'day2-linalg-3-task-3', description: '15 problems: Find basis for column space', completed: false },
          { id: 'day2-linalg-3-task-4', description: '15 problems: Find basis for null space', completed: false },
        ],
      },
    ],
  },
  // Adding Days 3-6 with key blocks - will be comprehensive
  {
    dayNumber: 3,
    date: 'Dec 7',
    blocks: [
      {
        id: 'day3-java-1',
        timeRange: '8:00–9:30',
        title: 'Interfaces',
        topic: 'Java',
        description: 'Interface methods are public abstract by default',
        completed: false,
        tasks: [
          { id: 'day3-java-1-task-1', description: 'Watch interface tutorial (~30 min)', completed: false },
          { id: 'day3-java-1-task-2', description: 'Solve a recreated Q35-style problem tracing why it fails to compile', completed: false },
        ],
      },
      {
        id: 'day3-java-2',
        timeRange: '9:30–11:00',
        title: 'Interface Practice',
        topic: 'Java',
        description: 'Implement Comparable, Printable interfaces',
        completed: false,
        tasks: [
          { id: 'day3-java-2-task-1', description: 'Implement Comparable<Student> for a Student class', completed: false },
          { id: 'day3-java-2-task-2', description: 'Implement a Printable interface for shapes with printInfo()', completed: false },
        ],
      },
      {
        id: 'day3-java-3',
        timeRange: '11:00–13:00',
        title: 'Polymorphism Deep Dive',
        topic: 'Java',
        description: 'Upcasting, instanceof, reference type vs object type',
        completed: false,
        tasks: [
          { id: 'day3-java-3-task-1', description: 'Solve a set of polymorphism problems analogous to mock Q6, Q16, Q17, Q26, Q33, Q34', completed: false },
          { id: 'day3-java-3-task-2', description: 'Create 10 custom polymorphism questions and solve them', completed: false },
        ],
      },
      {
        id: 'day3-linalg-1',
        timeRange: '14:00–15:00',
        title: 'Determinant Theory',
        topic: 'Linear Algebra',
        description: '2×2: det = ad - bc. 3×3: cofactor expansion',
        completed: false,
        tasks: [
          { id: 'day3-linalg-1-task-1', description: 'Watch Khan Academy "Computing determinants" (~20 min at 2x)', completed: false },
        ],
      },
      {
        id: 'day3-linalg-2',
        timeRange: '15:00–17:30',
        title: 'Determinant Speed Drills',
        topic: 'Linear Algebra',
        description: '20 problems: 2×2 (goal: <30s each). 40 problems: 3×3 (goal: <3 min each)',
        completed: false,
        tasks: [
          { id: 'day3-linalg-2-task-1', description: '20 problems: 2×2 determinants (goal: <30s each)', completed: false },
          { id: 'day3-linalg-2-task-2', description: '40 problems: 3×3 determinants (goal: <3 min each)', completed: false },
          { id: 'day3-linalg-2-task-3', description: '10 problems: 4×4 determinants via cofactor expansion', completed: false },
        ],
      },
      {
        id: 'day3-linalg-3',
        timeRange: '17:30–19:00',
        title: 'Inverses',
        topic: 'Linear Algebra',
        description: '2×2 inverse formula, 3×3 via row reduction',
        completed: false,
        tasks: [
          { id: 'day3-linalg-3-task-1', description: '15 problems: compute inverses', completed: false },
          { id: 'day3-linalg-3-task-2', description: '10 problems: determine if matrices are singular (non-invertible)', completed: false },
        ],
      },
    ],
  },
  {
    dayNumber: 4,
    date: 'Dec 8',
    blocks: [
      {
        id: 'day4-java-1',
        timeRange: '8:00–10:00',
        title: 'Access Modifiers',
        topic: 'Java',
        description: 'private, default, protected, public',
        completed: false,
        tasks: [
          { id: 'day4-java-1-task-1', description: 'Create two packages (p1, p2) and test access patterns similar to Q28–Q29', completed: false },
          { id: 'day4-java-1-task-2', description: 'Make 20 variations', completed: false },
        ],
      },
      {
        id: 'day4-java-2',
        timeRange: '10:00–11:30',
        title: 'Edge Cases',
        topic: 'Java',
        description: 'Compile vs runtime errors',
        completed: false,
        tasks: [
          { id: 'day4-java-2-task-1', description: 'Create 20 "Will this compile?" scenarios and label them', completed: false },
        ],
      },
      {
        id: 'day4-java-3',
        timeRange: '11:30–13:00',
        title: 'Overriding Rules',
        topic: 'Java',
        description: 'Valid vs invalid overriding scenarios',
        completed: false,
        tasks: [
          { id: 'day4-java-3-task-1', description: '15 override scenarios: valid vs invalid', completed: false },
        ],
      },
      {
        id: 'day4-linalg-1',
        timeRange: '14:00–15:00',
        title: 'Eigenvalue Theory',
        topic: 'Linear Algebra',
        description: 'Solve det(A − λI) = 0 for eigenvalues',
        completed: false,
        tasks: [
          { id: 'day4-linalg-1-task-1', description: 'Watch 3Blue1Brown Parts 6–7 (~1.5x speed)', completed: false },
        ],
      },
      {
        id: 'day4-linalg-2',
        timeRange: '15:00–19:00',
        title: 'Eigenvalue Marathon',
        topic: 'Linear Algebra',
        description: '30 problems: 2×2 (≤ 4 min each). 20 problems: 3×3 (≤ 8 min each)',
        completed: false,
        tasks: [
          { id: 'day4-linalg-2-task-1', description: '30 problems: 2×2 eigenvalues and eigenvectors (≤ 4 min each)', completed: false },
          { id: 'day4-linalg-2-task-2', description: '20 problems: 3×3 eigenvalues and eigenvectors (≤ 8 min each)', completed: false },
        ],
      },
    ],
  },
  {
    dayNumber: 5,
    date: 'Dec 9',
    blocks: [
      {
        id: 'day5-java-1',
        timeRange: '8:00–11:00',
        title: 'Full Java Mock Exam',
        topic: 'Java',
        description: 'Take the ES1036 mock exam (44 questions, 3 hours) under exam conditions',
        completed: false,
        tasks: [
          { id: 'day5-java-1-task-1', description: 'Take the ES1036 mock exam (44 questions, 3 hours) under exam conditions: Timed 3 hours, No notes, no help, no IDE', completed: false },
        ],
      },
      {
        id: 'day5-java-2',
        timeRange: '11:00–13:00',
        title: 'Grade & Analyze',
        topic: 'Java',
        description: 'Mark the exam, compute score, generate weakness list',
        completed: false,
        tasks: [
          { id: 'day5-java-2-task-1', description: 'Mark the exam. Compute total score; target ≥ 85/100', completed: false },
          { id: 'day5-java-2-task-2', description: 'For each missed question, tag: "Careless", "Concept gap", "Calculation error"', completed: false },
          { id: 'day5-java-2-task-3', description: 'Generate a "Java Weakness List"', completed: false },
        ],
      },
      {
        id: 'day5-linalg-1',
        timeRange: '14:00–15:00',
        title: 'Dot Products & Orthogonality',
        topic: 'Linear Algebra',
        description: 'u·v = u₁v₁ + ..., u·v = |u||v|cosθ',
        completed: false,
        tasks: [
          { id: 'day5-linalg-1-task-1', description: 'Watch 3Blue1Brown Part 2', completed: false },
        ],
      },
      {
        id: 'day5-linalg-2',
        timeRange: '15:00–16:30',
        title: 'Practice',
        topic: 'Linear Algebra',
        description: 'Dot products, orthogonality, projections',
        completed: false,
        tasks: [
          { id: 'day5-linalg-2-task-1', description: '20 problems: compute dot products in R², R³, Rⁿ', completed: false },
          { id: 'day5-linalg-2-task-2', description: '15 problems: check orthogonality', completed: false },
          { id: 'day5-linalg-2-task-3', description: '10 problems: compute projections onto another vector', completed: false },
        ],
      },
      {
        id: 'day5-linalg-3',
        timeRange: '16:30–19:00',
        title: 'Comprehensive Lin Alg Review',
        topic: 'Linear Algebra',
        description: 'One of each major type',
        completed: false,
        tasks: [
          { id: 'day5-linalg-3-task-1', description: 'Row reduction → rank → null space basis', completed: false },
          { id: 'day5-linalg-3-task-2', description: 'Linear independence check', completed: false },
          { id: 'day5-linalg-3-task-3', description: '3×3 determinant', completed: false },
          { id: 'day5-linalg-3-task-4', description: 'Inverse of 3×3', completed: false },
          { id: 'day5-linalg-3-task-5', description: 'Eigenvalues/eigenvectors', completed: false },
          { id: 'day5-linalg-3-task-6', description: 'Dot product + orthogonality', completed: false },
        ],
      },
    ],
  },
  {
    dayNumber: 6,
    date: 'Dec 10',
    blocks: [
      {
        id: 'day6-java-1',
        timeRange: '8:00–11:00',
        title: 'Code Writing Marathon',
        topic: 'Java',
        description: '6 programs, 30 min each',
        completed: false,
        tasks: [
          { id: 'day6-java-1-task-1', description: 'Matrix manipulation method like mock Q42: result = a/x + b*y for 2D double arrays', completed: false },
          { id: 'day6-java-1-task-2', description: 'Array of objects (Circle) with findMax like mock Q43', completed: false },
          { id: 'day6-java-1-task-3', description: 'Abstract class extension with toString like Q44 (Hexagon)', completed: false },
          { id: 'day6-java-1-task-4', description: 'Interface implementation program (e.g., multiple interfaces)', completed: false },
          { id: 'day6-java-1-task-5', description: 'Multi-level inheritance example with overriding (Person → Employee → Manager)', completed: false },
          { id: 'day6-java-1-task-6', description: 'Package access modifiers test program', completed: false },
        ],
      },
      {
        id: 'day6-java-2',
        timeRange: '11:00–13:00',
        title: 'Speed Drills',
        topic: 'Java',
        description: '20 MC-style questions, 3 code-tracing, 2 code-writing',
        completed: false,
        tasks: [
          { id: 'day6-java-2-task-1', description: '20 MC-style questions (~3 min each)', completed: false },
          { id: 'day6-java-2-task-2', description: '3 code-tracing problems (~10 min each)', completed: false },
          { id: 'day6-java-2-task-3', description: '2 code-writing questions (~20 min each)', completed: false },
        ],
      },
      {
        id: 'day6-linalg-1',
        timeRange: '14:00–17:00',
        title: 'Mixed Problem Marathon',
        topic: 'Linear Algebra',
        description: '60 mixed problems (~3 min each)',
        completed: false,
        tasks: [
          { id: 'day6-linalg-1-task-1', description: '10 row-reduction → RREF', completed: false },
          { id: 'day6-linalg-1-task-2', description: '10 rank/nullity problems', completed: false },
          { id: 'day6-linalg-1-task-3', description: '10 linear independence', completed: false },
          { id: 'day6-linalg-1-task-4', description: '10 determinants (3×3)', completed: false },
          { id: 'day6-linalg-1-task-5', description: '10 eigenvalues (2×2)', completed: false },
          { id: 'day6-linalg-1-task-6', description: '10 dot product / orthogonality / projection', completed: false },
        ],
      },
      {
        id: 'day6-linalg-2',
        timeRange: '17:00–19:00',
        title: 'Final Review',
        topic: 'Linear Algebra',
        description: 'Review all flashcards, construct formula sheet',
        completed: false,
        tasks: [
          { id: 'day6-linalg-2-task-1', description: 'Review all linear algebra flashcards (3 passes)', completed: false },
          { id: 'day6-linalg-2-task-2', description: 'Construct a 1-page formula sheet', completed: false },
        ],
      },
    ],
  },
];

export const resources: Resource[] = [
  {
    id: 'r1',
    title: 'Bro Code: Full Java Course',
    purpose: 'YouTube Java course - jump to OOP section (~4:00:00 mark)',
    link: 'https://www.youtube.com/results?search_query=Bro+Code+Full+Java+Course',
    subject: 'Java',
  },
  {
    id: 'r2',
    title: 'W3Schools Java reference',
    purpose: 'Comprehensive Java reference documentation',
    link: 'https://www.w3schools.com/java/',
    subject: 'Java',
  },
  {
    id: 'r5',
    title: '3Blue1Brown – Essence of Linear Algebra',
    purpose: 'Visual explanations of linear algebra concepts',
    link: 'https://www.3blue1brown.com/topics/linear-algebra',
    subject: 'Linear Algebra',
  },
  {
    id: 'r6',
    title: 'Khan Academy - Matrix Operations',
    purpose: 'Practice matrix operations, RREF, determinants, inverses',
    link: 'https://www.khanacademy.org/math/linear-algebra',
    subject: 'Linear Algebra',
  },
  {
    id: 'r7',
    title: 'MIT 18.06 notes',
    purpose: 'Rank, nullity, column space, null space',
    link: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/',
    subject: 'Linear Algebra',
  },
  {
    id: 'r8',
    title: 'Symbolab.com',
    purpose: 'Answer checking for matrix operations and linear algebra',
    link: 'https://www.symbolab.com/',
    subject: 'Linear Algebra',
  },
];

